export const ActionTypes = {
    SET_FORM: "SET_FORM",
    SET_FORM_ID: "SET_FORM_ID",
    REMOVE_FORM: "REMOVE_FORM",
    ADD_FORM_INPUT: "ADD_FORM_INPUT",
    SET_FORM_TITLE: "SET_FORM_TITLE",
    REMOVE_QUESTION: "REMOVE_QUESTION",
    DELETE_QUESTION: "DELETE_QUESTION",
}